export const CHANGE_SECTION = 'CHANGE_SECTION';
export const GET_MOVIES = 'GET_MOVIES';
export const GET_FAVOURITES = 'GET_FAVOURITES';
export const SET_FAVOURITE = 'SET_FAVOURITE';
export const REMOVE_FAVOURITE = 'REMOVE_FAVOURITE';
