export const CHANGE_SECTION = 'CHANGE_SECTION';
export const GET_MOVIES = 'GET_MOVIES';
export const GET_FAVOURITES = 'GET_FAVOURITES';
export const SET_FAVOURITE = 'SET_FAVOURITE';
export const REMOVE_FAVOURITE = 'REMOVE_FAVOURITE';
export const GET_DETAIL_REQUESTED = 'GET_DETAIL_REQUESTED';
export const GET_DETAIL_SUCCESS = 'GET_DETAIL_SUCCESS';
export const GET_DETAIL_FAIL = 'GET_DETAIL_FAIL';
export const GET_BACK = 'GET_BACK';

